### ISSUE TITLE
Failed to load JSON file.

### ISSUE THREAD

**Issue by atharvagadkari05** [DesignSystemsOSS/github-profile-ideas#11]
![image](https://user-images.githubusercontent.com/74293435/116923995-eef2b780-ac74-11eb-83c5-b7d7be4b9ae4.png)

The JSON file is not being able to load.

**Comment by nhcarrigan** [comment]
https://github.com/DesignSystemsOSS/github-profile-ideas/blob/7a342a5dce1f134e1fc7c828f7c4e6570cf22501/Views/app.js#L5

I believe it's due to this line - if you use a relative path `./Data/profile_data.json` it should work.

**Comment by atharvagadkari05** [comment]
We tried this but still, it's not working. @nhcarrigan

**Comment by atharvagadkari05** [comment]
@nhcarrigan  we tried but it doesn't work.

**Comment by v0idFuncti0n** [comment]
hello, I looked into the problem and it seems you have to run it from the server because the fetch method needs to have an URL starting with HTTP or HTTPS protocol once you do that it will work.
![site opened from the server](https://user-images.githubusercontent.com/48259478/116930714-a1b01f00-ac4f-11eb-881d-8fa72f7e08e3.PNG)

**Comment by nhcarrigan** [comment]
Sounds like a great addition to the documentation then 😉

**Comment by yashsehgal** [comment]
> hello, I looked into the problem and it seems you have to run it from the server because the fetch method needs to have an URL starting with HTTP or HTTPS protocol once you do that it will work.
> ![site opened from the server](https://user-images.githubusercontent.com/48259478/116930714-a1b01f00-ac4f-11eb-881d-8fa72f7e08e3.PNG)

Great @v0idFuncti0n, you can create a bugfix branch something like `bugfix/json-fix` and create a PR. 👍🏽

**Comment by pvcodes** [comment]
Is this issue fixed, because [`here`](https://designsystemsoss.github.io/github-profile-ideas/index.html), everything is fine!

**Comment by yashsehgal** [comment]
Thanks for reminding @pvcodes - This issue has been resolved but we forgot to close it!

**Comment by pvcodes** [comment]
NVM
